apiVersion: v1
kind: Secret
metadata:
  name: helm-oci-repo-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"%s\", \"auth\": \"%s\"}}}" .Values.ociRepo.url .Values.ociRepo.username .Values.ociRepo.password .Values.ociRepo.email (printf "%s:%s" .Values.ociRepo.username .Values.ociRepo.password | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson