apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  chart: {{ .Values.chartConfig.chart }}
#  repo: {{ .Values.chartConfig.repo }}
  version: {{ .Values.chartConfig.version }}
  targetNamespace: {{ .Values.chartConfig.namespace }}
{{- if .Values.chartConfig.dockerRegistrySecretName }}
  dockerRegistrySecret:
    name: {{ .Values.chartConfig.dockerRegistrySecretName }}
{{- end }}
  valuesContent: |-
{{ .Values.chartConfig.valuesContent | indent 4 }}
        