apiVersion: v2
name: argocd
description: argocd update chart including the repository configuration
version: "v0.1.0"
appVersion: "v0.1.0"
type: application
dependencies:
  - name: argocd-chart
    version: "0.2.0"
