{{- $proxy := "" -}}
{{- $noProxy := "" -}}
{{- if and .Values.global.proxy (ne .Values.global.proxy "") }}
{{- $proxy = .Values.global.proxy -}}
{{- end }}
{{- if and .Values.global.no_proxy (ne .Values.global.no_proxy "") }}
{{- $noProxy = .Values.global.no_proxy -}}
{{- end }}

{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-repo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: "{{ .url }}"
  {{- if $proxy }}
  proxy: {{ $proxy }}
  {{- end }}
  {{- if $noProxy }}
  noProxy: {{ $noProxy }}
  {{- end }}
  password: "{{ .token }}"
  username: "x-oauth-basic"
---
{{- end }}
